default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: learn_learn_graphql_development
test:
  <<: *default
  database: learn_learn_graphql_test
production:
  <<: *default
  database: learn_learn_graphql_production

  username: alex
  password: alex
